---
### Import zone

---

In [4]:
import pandas as pd
import numpy as np

---
### Load platform dataframe

---

In [5]:
platform_df = pd.read_csv('../data/clean/all_together_clean.csv')
platform_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,id,duration_int,duration_type
0,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021/03/30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,as1,113,min
1,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021/03/30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,as2,110,min
2,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021/03/30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,as3,74,min
3,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021/03/30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",as4,69,min
4,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021/03/30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,as5,45,min

In [6]:
platform_df.shape

(22998, 15)

---
### Load ratings dataframe

---

In [7]:
rating_df = pd.read_csv('../data/clean/all_ratings.csv')
rating_df.drop(columns=["Unnamed: 0"], axis=1, inplace=True)
rating_df.head()

   userId  rating   timestamp movieId
0       1     1.0  1425941529   as680
1       1     4.5  1425942435  ns2186
2       1     5.0  1425941523  hs2381
3       1     5.0  1425941546  ns3663
4       1     5.0  1425941556  as9500

---
### Get unique movies id

---

In [8]:
rating_df_short = rating_df[['movieId','rating']]
score_by_movie = rating_df_short.groupby('movieId').mean()
print(score_by_movie.head())

           rating
movieId
as1      3.467131
as10     3.439571
as100    3.609302
as1000   3.556701
as1001   3.585288

In [9]:
platform_df.set_index('id', inplace=True)

In [10]:
platform_df = platform_df.assign(score = score_by_movie)

In [11]:
# Promote id (index) to column again
platform_df = platform_df.reset_index()
platform_df

,id,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,duration_int,duration_type,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2021/03/30,2014,g,113 min,"comedy, drama",a small fishing village must procure a local d...,113,min,3.467131
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2021/03/30,2018,13+,110 min,"drama, international",a metro family decides to fight a cyber crimin...,110,min,3.548682
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2021/03/30,2017,g,74 min,"action, drama, suspense",after a man discovers his wife is cheating on ...,74,min,3.500000
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncé, britney...",united states,2021/03/30,2014,g,69 min,documentary,"pink breaks the mold once again, bringing her ...",69,min,3.538055
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,2021/03/30,1989,g,45 min,"drama, fantasy",teenage matt banting wants to work with a famo...,45,min,3.478992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,ns8803,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2019/11/20,2007,r,158 min,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",158,min,3.438998
22994,ns8804,s8804,tv show,zombie dumb,unknown director,unknown cast,unknown country,2019/07/1,2018,tv-y7,2 seasons,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",2,seasons,3.515947
22995,ns8805,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2019/11/1,2009,r,88 min,"comedies, horror movies",looking to survive in a world taken over by zo...,88,min,3.420945
22996,ns8806,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2020/01/11,2006,pg,88 min,"children & family movies, comedies","dragged from civilian life, a former superhero...",88,min,3.588050
22997,ns8807,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2019/03/2,2015,tv-14,111 min,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,111,min,3.529228

---
### Save the platform_df with the new score column to .csv

---

In [12]:
import os

# Individual

root_path = '../data/clean/'
isExist = os.path.exists(root_path)
if not isExist:
    # Create a new directory because it does not exist
    os.makedirs(root_path)

platform_df.to_csv(root_path+"all_together_with_score.csv")