![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Noelia's ML_OPS Project!  ðŸ‘»ðŸ‘»

###  Notebook: Merge users reviews with movie information

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

### Import zone

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [1]:
import pandas as pd
import numpy as np

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
### Load platform dataframe

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [2]:
platform_df = pd.read_csv('../data/clean/all_together_clean.csv')
platform_df.head()

,id,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,duration_int,duration_type
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2014,g,"comedy, drama",a small fishing village must procure a local d...,113,min
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2018,13+,"drama, international",a metro family decides to fight a cyber crimin...,110,min
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2017,g,"action, drama, suspense",after a man discovers his wife is cheating on ...,74,min
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncÃ©, britney...",united states,2014,g,documentary,"pink breaks the mold once again, bringing her ...",69,min
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,1989,g,"drama, fantasy",teenage matt banting wants to work with a famo...,45,min

In [3]:
platform_df.shape

(22998, 13)

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
### Load ratings dataframe

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [4]:
rating_df = pd.read_csv('../data/clean/all_ratings.csv')
rating_df.drop(columns=["Unnamed: 0"], axis=1, inplace=True)
rating_df.head()

   userId  score movieId
0       1    1.0   as680
1       1    4.5  ns2186
2       1    5.0  hs2381
3       1    5.0  ns3663
4       1    5.0  as9500

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
### Get unique movies id

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [5]:
rating_df_short = rating_df[['movieId','score']]
score_by_movie = rating_df_short.groupby('movieId').mean()

In [6]:
platform_df.set_index('id', inplace=True)

In [7]:
platform_df = platform_df.assign(score = score_by_movie)

In [8]:
# Promote id (index) to column again
platform_df = platform_df.reset_index()
platform_df

,id,show_id,type,title,director,cast,country,release_year,rating,listed_in,description,duration_int,duration_type,score
0,as1,s1,movie,the grand seduction,don mckellar,"brendan gleeson, taylor kitsch, gordon pinsent",canada,2014,g,"comedy, drama",a small fishing village must procure a local d...,113,min,3.467131
1,as2,s2,movie,take care good night,girish joshi,"mahesh manjrekar, abhay mahajan, sachin khedekar",india,2018,13+,"drama, international",a metro family decides to fight a cyber crimin...,110,min,3.548682
2,as3,s3,movie,secrets of deception,josh webber,"tom sizemore, lorenzo lamas, robert lasardo, r...",united states,2017,g,"action, drama, suspense",after a man discovers his wife is cheating on ...,74,min,3.500000
3,as4,s4,movie,pink: staying true,sonia anderson,"interviews with: pink, adele, beyoncÃ©, britney...",united states,2014,g,documentary,"pink breaks the mold once again, bringing her ...",69,min,3.538055
4,as5,s5,movie,monster maker,giles foster,"harry dean stanton, kieran o'brien, george cos...",united kingdom,1989,g,"drama, fantasy",teenage matt banting wants to work with a famo...,45,min,3.478992
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22993,ns8803,s8803,movie,zodiac,david fincher,"mark ruffalo, jake gyllenhaal, robert downey j...",united states,2007,r,"cult movies, dramas, thrillers","a political cartoonist, a crime reporter and a...",158,min,3.438998
22994,ns8804,s8804,tv show,zombie dumb,unknown director,unknown cast,unknown country,2018,tv-y7,"kids' tv, korean tv shows, tv comedies","while living alone in a spooky town, a young g...",2,seasons,3.515947
22995,ns8805,s8805,movie,zombieland,ruben fleischer,"jesse eisenberg, woody harrelson, emma stone, ...",united states,2009,r,"comedies, horror movies",looking to survive in a world taken over by zo...,88,min,3.420945
22996,ns8806,s8806,movie,zoom,peter hewitt,"tim allen, courteney cox, chevy chase, kate ma...",united states,2006,pg,"children & family movies, comedies","dragged from civilian life, a former superhero...",88,min,3.588050
22997,ns8807,s8807,movie,zubaan,mozez singh,"vicky kaushal, sarah-jane dias, raaghav chanan...",india,2015,tv-14,"dramas, international movies, music & musicals",a scrappy but poor boy worms his way into a ty...,111,min,3.529228

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
### Duration_type has a typo

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [9]:
platform_df['duration_type'].unique().tolist()

['min', 'season', 'seasons']

In [10]:
my_typo_dict = {
    'min':'min',
    'season':'seasons',
    'seasons':'seasons'
}
platform_df['duration_type'] = platform_df['duration_type'].map(lambda x: my_typo_dict[x])
platform_df['duration_type'].unique().tolist()

['min', 'seasons']

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)
### Save the platform_df with the new score column to .csv

![divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

In [11]:
import os

# Individual

root_path = '../data/clean/'
isExist = os.path.exists(root_path)
if not isExist:
    # Create a new directory because it does not exist
    os.makedirs(root_path)

platform_df.to_csv(root_path+"all_together_with_score.csv")